/// Type 19 and 20 are only in API v8. In v6, they are still type 0.
/// Type 21 is only in API v9.
enum DiscordMessageType {
  default0,
  recipientAdd,
  recipientRemove,
  call,
  channelNameChange,
  channelIconChange,
  channelPinnedMessage,
  guildMemberJoin,
  userPremiumGuildSubscription,
  userPremiumGuildSubscriptionTier1,
  userPremiumGuildSubscriptionTier2,
  userPremiumGuildSubscriptionTier3,
  channelFollowAdd,
  guildDiscoveryDisqualified,
  guildDiscoveryRequalified,
  guildDiscoveryGracePeriodInitialWarning,
  guildDiscoveryGracePeriodFinalWarning,
  threadCreated,
  reply,
  chatInputCommand,
  threadStarterMessage,
  guildInviteReminder,
  contextMenuCommand,
}
